/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "webhooks.handle": [
        {
            "name": "provider",
            "required": true
        }
    ],
    "developer.dashboard": [],
    "developer.stores.index": [],
    "developer.stores.create": [],
    "developer.stores.store": [],
    "developer.stores.show": [
        {
            "name": "store",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.stores.edit": [
        {
            "name": "store",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.stores.update": [
        {
            "name": "store",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.stores.destroy": [
        {
            "name": "store",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.stores.assign-owner": [
        {
            "name": "store",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.stores.revoke-owner": [
        {
            "name": "store",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.branches.index": [],
    "developer.stores.branches.index": [
        {
            "name": "store",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.stores.branches.create": [
        {
            "name": "store",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.stores.branches.store": [
        {
            "name": "store",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.stores.branches.edit": [
        {
            "name": "store",
            "required": true,
            "binding": "id"
        },
        {
            "name": "branch",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.stores.branches.update": [
        {
            "name": "store",
            "required": true,
            "binding": "id"
        },
        {
            "name": "branch",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.stores.branches.destroy": [
        {
            "name": "store",
            "required": true,
            "binding": "id"
        },
        {
            "name": "branch",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.users.index": [],
    "developer.users.create": [],
    "developer.users.store": [],
    "developer.users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.users.branches-json": [
        {
            "name": "store",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.plans.index": [],
    "developer.plans.create": [],
    "developer.plans.store": [],
    "developer.plans.edit": [
        {
            "name": "plan",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.plans.update": [
        {
            "name": "plan",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.plans.destroy": [
        {
            "name": "plan",
            "required": true,
            "binding": "id"
        }
    ],
    "developer.profile.edit": [],
    "developer.profile.update": [],
    "developer.profile.destroy": [],
    "admin.dashboard": [],
    "admin.store.select": [],
    "admin.store.select.post": [],
    "admin.store.switch": [],
    "admin.branch.select": [],
    "admin.branch.select.post": [],
    "admin.branch.switch": [],
    "admin.profile.edit": [],
    "admin.profile.update": [],
    "admin.profile.destroy": [],
    "admin.mutations.sync": [],
    "admin.master-data": [],
    "admin.kasir.index": [],
    "admin.kasir.store": [],
    "admin.payment-gateway.create": [],
    "admin.payment-gateway.status": [
        {
            "name": "pgTrxId",
            "required": true
        }
    ],
    "admin.payment-gateway.pending": [],
    "admin.cashier-shifts.index": [],
    "admin.cashier-shifts.show": [
        {
            "name": "cashierShift",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.cashier-shifts.create": [],
    "admin.cashier-shifts.store": [],
    "admin.cashier-shifts.close": [
        {
            "name": "cashierShift",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.cashier-shifts.update": [
        {
            "name": "cashierShift",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.cashier-shifts.destroy": [
        {
            "name": "cashierShift",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.cashier-shifts.reopen": [
        {
            "name": "cashierShift",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.sales.index": [],
    "admin.sales.show": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.sales.print": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.sales.create": [],
    "admin.sales.store": [],
    "admin.sales.switchPayment": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.sales.updateStatus": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.sales.destroy": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.sale-returns.index": [],
    "admin.sale-returns.create": [],
    "admin.sale-returns.store": [],
    "admin.sale-returns.show": [
        {
            "name": "sale_return",
            "required": true
        }
    ],
    "admin.sale-returns.destroy": [
        {
            "name": "sale_return",
            "required": true
        }
    ],
    "admin.sale-returns.updateStatus": [
        {
            "name": "saleReturn",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.sale-returns.getSaleItems": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.index": [],
    "admin.products.show": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.by-barcode": [],
    "admin.products.create": [],
    "admin.products.store": [],
    "admin.products.edit": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.variants.index": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.variants.store": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.variants.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        },
        {
            "name": "variant",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.variants.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        },
        {
            "name": "variant",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.recipes.index": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.recipes.store": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.recipes.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        },
        {
            "name": "recipe",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.modifier-groups.index": [],
    "admin.modifier-groups.create": [],
    "admin.modifier-groups.store": [],
    "admin.modifier-groups.show": [
        {
            "name": "modifier_group",
            "required": true
        }
    ],
    "admin.modifier-groups.edit": [
        {
            "name": "modifier_group",
            "required": true
        }
    ],
    "admin.modifier-groups.update": [
        {
            "name": "modifier_group",
            "required": true
        }
    ],
    "admin.modifier-groups.destroy": [
        {
            "name": "modifier_group",
            "required": true
        }
    ],
    "admin.modifier-groups.storeModifier": [
        {
            "name": "modifierGroup",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.modifier-groups.updateModifier": [
        {
            "name": "modifierGroup",
            "required": true,
            "binding": "id"
        },
        {
            "name": "modifier",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.modifier-groups.destroyModifier": [
        {
            "name": "modifierGroup",
            "required": true,
            "binding": "id"
        },
        {
            "name": "modifier",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.modifier-groups.attachProduct": [
        {
            "name": "modifierGroup",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.modifier-groups.detachProduct": [
        {
            "name": "modifierGroup",
            "required": true,
            "binding": "id"
        },
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categories.index": [],
    "admin.categories.create": [],
    "admin.categories.store": [],
    "admin.categories.show": [
        {
            "name": "category",
            "required": true
        }
    ],
    "admin.categories.edit": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.suppliers.index": [],
    "admin.suppliers.create": [],
    "admin.suppliers.store": [],
    "admin.suppliers.show": [
        {
            "name": "supplier",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.suppliers.edit": [
        {
            "name": "supplier",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.suppliers.update": [
        {
            "name": "supplier",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.suppliers.destroy": [
        {
            "name": "supplier",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.stock.index": [],
    "admin.stock.movements": [],
    "admin.product-batches.index": [],
    "admin.product-batches.create": [],
    "admin.product-batches.store": [],
    "admin.product-batches.edit": [
        {
            "name": "product_batch",
            "required": true
        }
    ],
    "admin.product-batches.update": [
        {
            "name": "product_batch",
            "required": true
        }
    ],
    "admin.product-batches.destroy": [
        {
            "name": "product_batch",
            "required": true
        }
    ],
    "admin.stock-adjustments.index": [],
    "admin.stock-adjustments.create": [],
    "admin.stock-adjustments.store": [],
    "admin.stock-adjustments.show": [
        {
            "name": "stock_adjustment",
            "required": true
        }
    ],
    "admin.stock-adjustments.destroy": [
        {
            "name": "stock_adjustment",
            "required": true
        }
    ],
    "admin.stock-adjustments.updateStatus": [
        {
            "name": "stockAdjustment",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.stock-opnames.index": [],
    "admin.stock-opnames.create": [],
    "admin.stock-opnames.store": [],
    "admin.stock-opnames.show": [
        {
            "name": "stock_opname",
            "required": true
        }
    ],
    "admin.stock-opnames.destroy": [
        {
            "name": "stock_opname",
            "required": true
        }
    ],
    "admin.stock-opnames.updateStatus": [
        {
            "name": "stockOpname",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.stock-transfers.index": [],
    "admin.stock-transfers.create": [],
    "admin.stock-transfers.store": [],
    "admin.stock-transfers.show": [
        {
            "name": "stock_transfer",
            "required": true
        }
    ],
    "admin.stock-transfers.destroy": [
        {
            "name": "stock_transfer",
            "required": true
        }
    ],
    "admin.stock-transfers.updateStatus": [
        {
            "name": "stockTransfer",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.wastes.index": [],
    "admin.wastes.create": [],
    "admin.wastes.store": [],
    "admin.wastes.show": [
        {
            "name": "waste",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.wastes.destroy": [
        {
            "name": "waste",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.wastes.updateStatus": [
        {
            "name": "waste",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.purchases.index": [],
    "admin.purchases.show": [
        {
            "name": "purchase",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.purchases.create": [],
    "admin.purchases.store": [],
    "admin.purchases.updateStatus": [
        {
            "name": "purchase",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.purchases.destroy": [
        {
            "name": "purchase",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.purchase-returns.index": [],
    "admin.purchase-returns.create": [],
    "admin.purchase-returns.store": [],
    "admin.purchase-returns.show": [
        {
            "name": "purchase_return",
            "required": true
        }
    ],
    "admin.purchase-returns.destroy": [
        {
            "name": "purchase_return",
            "required": true
        }
    ],
    "admin.purchase-returns.updateStatus": [
        {
            "name": "purchaseReturn",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.purchase-returns.getPurchaseItems": [
        {
            "name": "purchase",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.customers.index": [],
    "admin.customers.create": [],
    "admin.customers.store": [],
    "admin.customers.show": [
        {
            "name": "customer",
            "required": true
        }
    ],
    "admin.customers.edit": [
        {
            "name": "customer",
            "required": true
        }
    ],
    "admin.customers.update": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.customers.destroy": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.employees.index": [],
    "admin.employees.create": [],
    "admin.employees.store": [],
    "admin.employees.edit": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.employees.update": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.employees.destroy": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.expenses.index": [],
    "admin.expenses.create": [],
    "admin.expenses.store": [],
    "admin.expenses.show": [
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.expenses.destroy": [
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.expenses.updateStatus": [
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.expense-categories.index": [],
    "admin.expense-categories.create": [],
    "admin.expense-categories.store": [],
    "admin.expense-categories.edit": [
        {
            "name": "expense_category",
            "required": true
        }
    ],
    "admin.expense-categories.update": [
        {
            "name": "expense_category",
            "required": true
        }
    ],
    "admin.expense-categories.destroy": [
        {
            "name": "expense_category",
            "required": true
        }
    ],
    "admin.promotions.index": [],
    "admin.promotions.show": [
        {
            "name": "promotion",
            "required": true
        }
    ],
    "admin.promotions.create": [],
    "admin.promotions.store": [],
    "admin.promotions.edit": [
        {
            "name": "promotion",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.promotions.update": [
        {
            "name": "promotion",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.promotions.destroy": [
        {
            "name": "promotion",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.cafe-tables.index": [],
    "admin.cafe-tables.create": [],
    "admin.cafe-tables.store": [],
    "admin.cafe-tables.edit": [
        {
            "name": "cafe_table",
            "required": true
        }
    ],
    "admin.cafe-tables.update": [
        {
            "name": "cafe_table",
            "required": true
        }
    ],
    "admin.cafe-tables.destroy": [
        {
            "name": "cafe_table",
            "required": true
        }
    ],
    "admin.cafe-tables.free": [
        {
            "name": "cafeTable",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.reports.index": [],
    "admin.reports.ask-ai": [],
    "admin.activity-logs.index": [],
    "admin.settings.index": [],
    "admin.settings.update": [],
    "admin.payment-methods.index": [],
    "admin.payment-methods.create": [],
    "admin.payment-methods.store": [],
    "admin.payment-methods.edit": [
        {
            "name": "payment_method",
            "required": true
        }
    ],
    "admin.payment-methods.update": [
        {
            "name": "payment_method",
            "required": true
        }
    ],
    "admin.payment-methods.destroy": [
        {
            "name": "payment_method",
            "required": true
        }
    ],
    "admin.payment-methods.toggle": [
        {
            "name": "payment_method",
            "required": true
        }
    ],
    "admin.payment-methods.sort": [
        {
            "name": "payment_method",
            "required": true
        }
    ],
    "admin.payment-methods.pg.save": [
        {
            "name": "provider",
            "required": true
        }
    ],
    "admin.roles.index": [],
    "admin.roles.store": [],
    "admin.roles.update": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.roles.destroy": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.store-users.index": [],
    "admin.store-users.invite": [],
    "admin.store-users.assign-role": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.store-users.revoke": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
