import {
    Archive,
    ArrowLeftRight,
    BadgeDollarSign,
    Banknote,
    BarChart3,
    Boxes,
    Calendar,
    CheckCircle,
    ClipboardList,
    Clock,
    Cog,
    CookingPot,
    CreditCard,
    Database,
    DollarSign,
    FileText,
    FolderTree,
    Home,
    Layers,
    LayoutDashboard,
    List,
    ListChecks,
    Package,
    Palette,
    Receipt,
    ShoppingBag,
    ShoppingCart,
    SlidersHorizontal,
    Table,
    Tag,
    Trash2,
    TrendingUp,
    Truck,
    Undo2,
    User,
    Users,
    UtensilsCrossed,
    Wallet,
    Zap,
} from "lucide-react";

const ICONS = {
    dashboard: LayoutDashboard,
    pos: ShoppingCart,
    product: Package,
    category: FolderTree,
    customer: Users,
    supplier: Truck,
    employee: User,
    sales: ClipboardList,
    purchase: ShoppingBag,
    retur: Undo2,
    promo: Tag,
    expense: DollarSign,
    shift: Clock,
    stock: Boxes,
    batch: Layers,
    adjustment: SlidersHorizontal,
    opname: CheckCircle,
    transfer: ArrowLeftRight,
    waste: Trash2,
    modifier: ListChecks,
    report: BarChart3,
    reportSales: TrendingUp,
    reportPurchase: ShoppingBag,
    reportStock: Boxes,
    reportExpense: Receipt,
    reportShift: Clock,
    reportCommission: BadgeDollarSign,
    payment: CreditCard,
    debt: Banknote,
    settings: Cog,
    table: Table,
    kitchen: CookingPot,
    queue: List,
    booking: Calendar,
    membership: CreditCard,
    commission: Banknote,
    recipe: FileText,
    users: Users,
    shield: CheckCircle,
    log: FileText,
    theme: Palette,
    wallet: Wallet,
    paymentGw: CreditCard,
};

const GROUP_ICONS = {
    home: Home,
    lightning: Zap,
    database: Database,
    arrowsRightLeft: ArrowLeftRight,
    archiveBox: Archive,
    currencyDollar: DollarSign,
    cog: Cog,
};

export function NavIcons({ name, className = "h-4 w-4" }) {
    const Icon = ICONS[name] ?? ICONS.product;
    return <Icon className={className} strokeWidth={1.7} />;
}

export function GroupIcons({ name, className = "h-4 w-4" }) {
    const Icon = GROUP_ICONS[name] ?? GROUP_ICONS.home;
    return <Icon className={className} strokeWidth={1.7} />;
}
